// @ts-nocheck
// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
// Bypasses TS6133. Allow declared but unused functions.
// @ts-ignore
function id(d: any[]): any {
	return d[0];
}
declare var semicolon: any;
declare var NL: any;
declare var ws: any;
declare var colon: any;
declare var langle: any;
declare var rangle: any;
declare var op: any;
declare var hole: any;
declare var lparens: any;
declare var rparens: any;
declare var arrow: any;
declare var backslash: any;
declare var hash: any;
declare var fatArrow: any;
declare var lbracket: any;
declare var rbracket: any;
declare var comma: any;
declare var bar: any;
declare var lbrace: any;
declare var rbrace: any;
declare var equals: any;
declare var dot: any;
declare var variable: any;
declare var digit: any;
declare var string: any;

// Moo lexer documentation is here:
// https://github.com/no-context/moo

import moo from "moo";
import * as Q from "@qtt/shared/modalities/multiplicity";
import * as Lit from "@qtt/shared/literals";
import * as P from "./processors";

const lexer = moo.compile({
	digit: { match: /[0-9]+/, value: s => parseInt(s) },
	string: { match: /"(?:\\["bfnrt\/\\]|\\u[a-fA-F0-9]{4}|[^"\\])*"/, value: s => s.slice(1, -1) },
	variable: { match: /[a-zA-Z][a-zA-Z0-9]*/, type: moo.keywords({ ret: "return", dec: "let", match: "match", Type: "Type", Unit: "Unit", Row: "Row" }) },
	dot: /\./,
	equals: /\=(?!>)/,
	backslash: /\\/,
	arrow: /->/,
	fatArrow: /\=>/,
	op: /[\+\-\*\/]/,
	ws: /[ \t]+/,
	lparens: /\(/,
	rparens: /\)/,
	lbrace: /\{/,
	rbrace: /\}/,
	langle: /</,
	rangle: />/,
	lbracket: /\[/,
	rbracket: /\]/,
	semicolon: /\;/,
	colon: /\:/,
	comma: /\,/,
	bar: /\|/,
	hash: /#/,
	hole: /_/,
	NL: { match: /\n+/, lineBreaks: true },
});

interface NearleyToken {
	value: any;
	[key: string]: any;
}

interface NearleyLexer {
	reset: (chunk: string, info: any) => void;
	next: () => NearleyToken | undefined;
	save: () => any;
	formatError: (token: never) => string;
	has: (tokenType: string) => boolean;
}

interface NearleyRule {
	name: string;
	symbols: NearleySymbol[];
	postprocess?: (d: any[], loc?: number, reject?: {}) => any;
}

type NearleySymbol = string | { literal: any } | { test: (token: any) => boolean };

interface Grammar {
	Lexer: NearleyLexer | undefined;
	ParserRules: NearleyRule[];
	ParserStart: string;
}

const grammar: Grammar = {
	Lexer: lexer,
	ParserRules: [
		{ name: "Script$macrocall$2", symbols: ["Statement"] },
		{ name: "Script$macrocall$3", symbols: [lexer.has("semicolon") ? { type: "semicolon" } : semicolon] },
		{ name: "Script$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Script$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Script$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Script$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Script$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Script$macrocall$2",
				"Script$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Script$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Script$macrocall$3",
			],
		},
		{
			name: "Script$macrocall$1$ebnf$1",
			symbols: ["Script$macrocall$1$ebnf$1", "Script$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Script$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Script$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Script$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Script$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Script$macrocall$1",
			symbols: ["Script$macrocall$1$ebnf$1", "Script$macrocall$1$ebnf$2", "Script$macrocall$1$ebnf$3", "Script$macrocall$2"],
			postprocess: P.many,
		},
		{ name: "Script$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Script$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Script", symbols: ["Script$macrocall$1", lexer.has("semicolon") ? { type: "semicolon" } : semicolon, "Script$ebnf$1"], postprocess: P.script },
		{ name: "Ann$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Ann$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Ann$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Ann$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Ann", symbols: ["Ann", "Ann$ebnf$1", lexer.has("colon") ? { type: "colon" } : colon, "Ann$ebnf$2", "TypeExpr"], postprocess: P.Annotation },
		{ name: "Ann$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Ann$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Ann$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Ann$ebnf$4", symbols: [], postprocess: () => null },
		{ name: "Ann$macrocall$2", symbols: ["Quantity"] },
		{ name: "Ann$macrocall$1$macrocall$2", symbols: ["Ann$macrocall$2"] },
		{ name: "Ann$macrocall$1$macrocall$3", symbols: [lexer.has("langle") ? { type: "langle" } : langle] },
		{ name: "Ann$macrocall$1$macrocall$4", symbols: [lexer.has("rangle") ? { type: "rangle" } : rangle] },
		{ name: "Ann$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Ann$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Ann$macrocall$1$macrocall$1",
			symbols: ["Ann$macrocall$1$macrocall$3", "Ann$macrocall$1$macrocall$2", "Ann$macrocall$1$macrocall$1$ebnf$1", "Ann$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Ann$macrocall$1", symbols: ["Ann$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Ann$ebnf$5", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Ann$ebnf$5", symbols: [], postprocess: () => null },
		{
			name: "Ann",
			symbols: ["Ann", "Ann$ebnf$3", lexer.has("colon") ? { type: "colon" } : colon, "Ann$ebnf$4", "Ann$macrocall$1", "Ann$ebnf$5", "TypeExpr"],
			postprocess: P.Annotation,
		},
		{ name: "Ann", symbols: ["TypeExpr"], postprocess: id },
		{ name: "TypeExpr", symbols: ["Pi"], postprocess: id },
		{ name: "TypeExpr", symbols: ["Type"], postprocess: id },
		{ name: "Type", symbols: ["Mu"], postprocess: id },
		{ name: "Type", symbols: ["Variant"], postprocess: id },
		{ name: "Type", symbols: ["Schema"], postprocess: id },
		{ name: "Type", symbols: ["Row"], postprocess: id },
		{ name: "Type", symbols: ["Expr"], postprocess: id },
		{ name: "Expr", symbols: ["Lambda"], postprocess: id },
		{ name: "Expr", symbols: ["Match"], postprocess: id },
		{ name: "Expr", symbols: ["Block"], postprocess: id },
		{ name: "Expr", symbols: ["App"], postprocess: id },
		{ name: "App", symbols: ["App", lexer.has("ws") ? { type: "ws" } : ws, "Expr"], postprocess: P.Application },
		{ name: "App$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "App$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "App$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "App$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "App", symbols: ["App", "App$ebnf$1", lexer.has("op") ? { type: "op" } : op, "App$ebnf$2", "Expr"], postprocess: P.Operation },
		{ name: "App", symbols: ["Atom"], postprocess: id },
		{ name: "Atom", symbols: ["Identifier"], postprocess: P.Var },
		{ name: "Atom", symbols: [lexer.has("hole") ? { type: "hole" } : hole], postprocess: P.Hole },
		{ name: "Atom", symbols: ["Projection"], postprocess: id },
		{ name: "Atom", symbols: ["Injection"], postprocess: id },
		{ name: "Atom", symbols: ["Literal"], postprocess: P.Lit },
		{ name: "Atom", symbols: ["Struct"], postprocess: id },
		{ name: "Atom", symbols: ["Tuple"], postprocess: id },
		{ name: "Atom", symbols: ["List"], postprocess: id },
		{ name: "Atom", symbols: ["Tagged"], postprocess: id },
		{ name: "Atom$macrocall$2", symbols: ["Ann"] },
		{ name: "Atom$macrocall$1$macrocall$2", symbols: ["Atom$macrocall$2"] },
		{ name: "Atom$macrocall$1$macrocall$3", symbols: [lexer.has("lparens") ? { type: "lparens" } : lparens] },
		{ name: "Atom$macrocall$1$macrocall$4", symbols: [lexer.has("rparens") ? { type: "rparens" } : rparens] },
		{ name: "Atom$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Atom$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Atom$macrocall$1$macrocall$1",
			symbols: ["Atom$macrocall$1$macrocall$3", "Atom$macrocall$1$macrocall$2", "Atom$macrocall$1$macrocall$1$ebnf$1", "Atom$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Atom$macrocall$1", symbols: ["Atom$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Atom", symbols: ["Atom$macrocall$1"], postprocess: P.extract },
		{ name: "Mu$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Mu$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Mu$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Mu$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Mu$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Mu$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Mu",
			symbols: [{ literal: "μ" }, "Mu$ebnf$1", "Identifier", "Mu$ebnf$2", lexer.has("arrow") ? { type: "arrow" } : arrow, "Mu$ebnf$3", "TypeExpr"],
			postprocess: P.Mu,
		},
		{
			name: "Lambda",
			symbols: [
				lexer.has("backslash") ? { type: "backslash" } : backslash,
				"Param",
				lexer.has("ws") ? { type: "ws" } : ws,
				lexer.has("arrow") ? { type: "arrow" } : arrow,
				lexer.has("ws") ? { type: "ws" } : ws,
				"TypeExpr",
			],
			postprocess: P.Lambda,
		},
		{
			name: "Lambda",
			symbols: [
				lexer.has("backslash") ? { type: "backslash" } : backslash,
				lexer.has("hash") ? { type: "hash" } : hash,
				"Param",
				lexer.has("ws") ? { type: "ws" } : ws,
				lexer.has("fatArrow") ? { type: "fatArrow" } : fatArrow,
				lexer.has("ws") ? { type: "ws" } : ws,
				"TypeExpr",
			],
			postprocess: P.Lambda,
		},
		{ name: "Param", symbols: ["Identifier"], postprocess: P.Param },
		{ name: "Param$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Param$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$ebnf$2", symbols: [], postprocess: () => null },
		{
			name: "Param",
			symbols: ["Identifier", "Param$ebnf$1", lexer.has("colon") ? { type: "colon" } : colon, "Param$ebnf$2", "TypeExpr"],
			postprocess: P.Param,
		},
		{ name: "Param$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Param$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$ebnf$4", symbols: [], postprocess: () => null },
		{ name: "Param$macrocall$2", symbols: ["Quantity"] },
		{ name: "Param$macrocall$1$macrocall$2", symbols: ["Param$macrocall$2"] },
		{ name: "Param$macrocall$1$macrocall$3", symbols: [lexer.has("langle") ? { type: "langle" } : langle] },
		{ name: "Param$macrocall$1$macrocall$4", symbols: [lexer.has("rangle") ? { type: "rangle" } : rangle] },
		{ name: "Param$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Param$macrocall$1$macrocall$1",
			symbols: ["Param$macrocall$1$macrocall$3", "Param$macrocall$1$macrocall$2", "Param$macrocall$1$macrocall$1$ebnf$1", "Param$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Param$macrocall$1", symbols: ["Param$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Param$ebnf$5", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$ebnf$5", symbols: [], postprocess: () => null },
		{
			name: "Param",
			symbols: ["Identifier", "Param$ebnf$3", lexer.has("colon") ? { type: "colon" } : colon, "Param$ebnf$4", "Param$macrocall$1", "Param$ebnf$5", "TypeExpr"],
			postprocess: P.Param,
		},
		{ name: "Param$macrocall$4", symbols: ["Param"] },
		{ name: "Param$macrocall$3$macrocall$2", symbols: ["Param$macrocall$4"] },
		{ name: "Param$macrocall$3$macrocall$3", symbols: [lexer.has("lparens") ? { type: "lparens" } : lparens] },
		{ name: "Param$macrocall$3$macrocall$4", symbols: [lexer.has("rparens") ? { type: "rparens" } : rparens] },
		{ name: "Param$macrocall$3$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Param$macrocall$3$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Param$macrocall$3$macrocall$1",
			symbols: ["Param$macrocall$3$macrocall$3", "Param$macrocall$3$macrocall$2", "Param$macrocall$3$macrocall$1$ebnf$1", "Param$macrocall$3$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Param$macrocall$3", symbols: ["Param$macrocall$3$macrocall$1"], postprocess: P.enclosed },
		{ name: "Param", symbols: ["Param$macrocall$3"], postprocess: P.extract },
		{ name: "Pi$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Pi$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Pi$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Pi$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Pi", symbols: ["Type", "Pi$ebnf$1", lexer.has("arrow") ? { type: "arrow" } : arrow, "Pi$ebnf$2", "PiTail"], postprocess: P.Pi("Explicit") },
		{ name: "Pi$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Pi$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Pi$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Pi$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Pi",
			symbols: ["Type", "Pi$ebnf$3", lexer.has("fatArrow") ? { type: "fatArrow" } : fatArrow, "Pi$ebnf$4", "PiTail"],
			postprocess: P.Pi("Implicit"),
		},
		{ name: "PiTail", symbols: ["Pi"], postprocess: id },
		{ name: "PiTail", symbols: ["Type"], postprocess: id },
		{ name: "Row$macrocall$2", symbols: [lexer.has("lbracket") ? { type: "lbracket" } : lbracket] },
		{ name: "Row$macrocall$3", symbols: [lexer.has("rbracket") ? { type: "rbracket" } : rbracket] },
		{ name: "Row$macrocall$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Row$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Row$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Row$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Row$macrocall$1",
			symbols: ["Row$macrocall$2", "Row$macrocall$1$ebnf$1", "Row$macrocall$1$ebnf$2", "Row$macrocall$1$ebnf$3", "Row$macrocall$3"],
			postprocess: P.none,
		},
		{ name: "Row", symbols: ["Row$macrocall$1"], postprocess: P.emptyRow },
		{ name: "Row$macrocall$5$macrocall$2", symbols: ["KeyVal"] },
		{ name: "Row$macrocall$5$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Row$macrocall$5$macrocall$2",
				"Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Row$macrocall$5$macrocall$3",
			],
		},
		{
			name: "Row$macrocall$5$macrocall$1$ebnf$1",
			symbols: ["Row$macrocall$5$macrocall$1$ebnf$1", "Row$macrocall$5$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Row$macrocall$5$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Row$macrocall$5$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Row$macrocall$5$macrocall$1",
			symbols: [
				"Row$macrocall$5$macrocall$1$ebnf$1",
				"Row$macrocall$5$macrocall$1$ebnf$2",
				"Row$macrocall$5$macrocall$1$ebnf$3",
				"Row$macrocall$5$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "Row$macrocall$5$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "Row$macrocall$5$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Row$macrocall$5", symbols: ["Row$macrocall$5$macrocall$1", "Row$macrocall$5$ebnf$1"] },
		{ name: "Row$macrocall$4$macrocall$2", symbols: ["Row$macrocall$5"] },
		{ name: "Row$macrocall$4$macrocall$3", symbols: [lexer.has("lbracket") ? { type: "lbracket" } : lbracket] },
		{ name: "Row$macrocall$4$macrocall$4", symbols: [lexer.has("rbracket") ? { type: "rbracket" } : rbracket] },
		{ name: "Row$macrocall$4$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Row$macrocall$4$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Row$macrocall$4$macrocall$1",
			symbols: ["Row$macrocall$4$macrocall$3", "Row$macrocall$4$macrocall$2", "Row$macrocall$4$macrocall$1$ebnf$1", "Row$macrocall$4$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Row$macrocall$4", symbols: ["Row$macrocall$4$macrocall$1"], postprocess: P.enclosed },
		{ name: "Row", symbols: ["Row$macrocall$4"], postprocess: P.row },
		{ name: "RowTail$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "RowTail$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "RowTail$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "RowTail$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "RowTail", symbols: ["RowTail$ebnf$1", lexer.has("bar") ? { type: "bar" } : bar, "RowTail$ebnf$2", "Identifier"], postprocess: d => d[3] },
		{ name: "Struct$macrocall$2", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Struct$macrocall$3", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Struct$macrocall$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Struct$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Struct$macrocall$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Struct$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Struct$macrocall$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Struct$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Struct$macrocall$1",
			symbols: ["Struct$macrocall$2", "Struct$macrocall$1$ebnf$1", "Struct$macrocall$1$ebnf$2", "Struct$macrocall$1$ebnf$3", "Struct$macrocall$3"],
			postprocess: P.none,
		},
		{ name: "Struct", symbols: ["Struct$macrocall$1"], postprocess: P.emptyStruct },
		{ name: "Struct$macrocall$5$macrocall$2", symbols: ["KeyVal"] },
		{ name: "Struct$macrocall$5$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Struct$macrocall$5$macrocall$2",
				"Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Struct$macrocall$5$macrocall$3",
			],
		},
		{
			name: "Struct$macrocall$5$macrocall$1$ebnf$1",
			symbols: ["Struct$macrocall$5$macrocall$1$ebnf$1", "Struct$macrocall$5$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Struct$macrocall$5$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Struct$macrocall$5$macrocall$1",
			symbols: [
				"Struct$macrocall$5$macrocall$1$ebnf$1",
				"Struct$macrocall$5$macrocall$1$ebnf$2",
				"Struct$macrocall$5$macrocall$1$ebnf$3",
				"Struct$macrocall$5$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "Struct$macrocall$5", symbols: ["Struct$macrocall$5$macrocall$1"] },
		{ name: "Struct$macrocall$4$macrocall$2", symbols: ["Struct$macrocall$5"] },
		{ name: "Struct$macrocall$4$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Struct$macrocall$4$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Struct$macrocall$4$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Struct$macrocall$4$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Struct$macrocall$4$macrocall$1",
			symbols: ["Struct$macrocall$4$macrocall$3", "Struct$macrocall$4$macrocall$2", "Struct$macrocall$4$macrocall$1$ebnf$1", "Struct$macrocall$4$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Struct$macrocall$4", symbols: ["Struct$macrocall$4$macrocall$1"], postprocess: P.enclosed },
		{ name: "Struct", symbols: ["Struct$macrocall$4"], postprocess: P.struct },
		{ name: "Tuple$macrocall$2$macrocall$2", symbols: ["TypeExpr"] },
		{ name: "Tuple$macrocall$2$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Tuple$macrocall$2$macrocall$2",
				"Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Tuple$macrocall$2$macrocall$3",
			],
		},
		{
			name: "Tuple$macrocall$2$macrocall$1$ebnf$1",
			symbols: ["Tuple$macrocall$2$macrocall$1$ebnf$1", "Tuple$macrocall$2$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Tuple$macrocall$2$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Tuple$macrocall$2$macrocall$1",
			symbols: [
				"Tuple$macrocall$2$macrocall$1$ebnf$1",
				"Tuple$macrocall$2$macrocall$1$ebnf$2",
				"Tuple$macrocall$2$macrocall$1$ebnf$3",
				"Tuple$macrocall$2$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "Tuple$macrocall$2", symbols: ["Tuple$macrocall$2$macrocall$1"] },
		{ name: "Tuple$macrocall$1$macrocall$2", symbols: ["Tuple$macrocall$2"] },
		{ name: "Tuple$macrocall$1$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Tuple$macrocall$1$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Tuple$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Tuple$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Tuple$macrocall$1$macrocall$1",
			symbols: ["Tuple$macrocall$1$macrocall$3", "Tuple$macrocall$1$macrocall$2", "Tuple$macrocall$1$macrocall$1$ebnf$1", "Tuple$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Tuple$macrocall$1", symbols: ["Tuple$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Tuple", symbols: ["Tuple$macrocall$1"], postprocess: P.tuple },
		{ name: "List$macrocall$2$macrocall$2", symbols: ["TypeExpr"] },
		{ name: "List$macrocall$2$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1", symbols: [] },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"List$macrocall$2$macrocall$2",
				"List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"List$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"List$macrocall$2$macrocall$3",
			],
		},
		{
			name: "List$macrocall$2$macrocall$1$ebnf$1",
			symbols: ["List$macrocall$2$macrocall$1$ebnf$1", "List$macrocall$2$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "List$macrocall$2$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "List$macrocall$2$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "List$macrocall$2$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "List$macrocall$2$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "List$macrocall$2$macrocall$1",
			symbols: [
				"List$macrocall$2$macrocall$1$ebnf$1",
				"List$macrocall$2$macrocall$1$ebnf$2",
				"List$macrocall$2$macrocall$1$ebnf$3",
				"List$macrocall$2$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "List$macrocall$2", symbols: ["List$macrocall$2$macrocall$1"] },
		{ name: "List$macrocall$1$macrocall$2", symbols: ["List$macrocall$2"] },
		{ name: "List$macrocall$1$macrocall$3", symbols: [lexer.has("lbracket") ? { type: "lbracket" } : lbracket] },
		{ name: "List$macrocall$1$macrocall$4", symbols: [lexer.has("rbracket") ? { type: "rbracket" } : rbracket] },
		{ name: "List$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "List$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "List$macrocall$1$macrocall$1",
			symbols: ["List$macrocall$1$macrocall$3", "List$macrocall$1$macrocall$2", "List$macrocall$1$macrocall$1$ebnf$1", "List$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "List$macrocall$1", symbols: ["List$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "List", symbols: ["List$macrocall$1"], postprocess: P.list },
		{ name: "Schema$macrocall$2$macrocall$2", symbols: ["SchemaPair"] },
		{ name: "Schema$macrocall$2$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Schema$macrocall$2$macrocall$2",
				"Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Schema$macrocall$2$macrocall$3",
			],
		},
		{
			name: "Schema$macrocall$2$macrocall$1$ebnf$1",
			symbols: ["Schema$macrocall$2$macrocall$1$ebnf$1", "Schema$macrocall$2$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Schema$macrocall$2$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Schema$macrocall$2$macrocall$1",
			symbols: [
				"Schema$macrocall$2$macrocall$1$ebnf$1",
				"Schema$macrocall$2$macrocall$1$ebnf$2",
				"Schema$macrocall$2$macrocall$1$ebnf$3",
				"Schema$macrocall$2$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "Schema$macrocall$2$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "Schema$macrocall$2$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Schema$macrocall$2", symbols: ["Schema$macrocall$2$macrocall$1", "Schema$macrocall$2$ebnf$1"] },
		{ name: "Schema$macrocall$1$macrocall$2", symbols: ["Schema$macrocall$2"] },
		{ name: "Schema$macrocall$1$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Schema$macrocall$1$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Schema$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Schema$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Schema$macrocall$1$macrocall$1",
			symbols: ["Schema$macrocall$1$macrocall$3", "Schema$macrocall$1$macrocall$2", "Schema$macrocall$1$macrocall$1$ebnf$1", "Schema$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Schema$macrocall$1", symbols: ["Schema$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Schema", symbols: ["Schema$macrocall$1"], postprocess: P.schema },
		{ name: "Variant$macrocall$2", symbols: ["KeyVal"] },
		{ name: "Variant$macrocall$3", symbols: [lexer.has("bar") ? { type: "bar" } : bar] },
		{ name: "Variant$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Variant$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Variant$macrocall$2",
				"Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Variant$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Variant$macrocall$3",
			],
		},
		{
			name: "Variant$macrocall$1$ebnf$1",
			symbols: ["Variant$macrocall$1$ebnf$1", "Variant$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Variant$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Variant$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Variant$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Variant$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Variant$macrocall$1",
			symbols: ["Variant$macrocall$1$ebnf$1", "Variant$macrocall$1$ebnf$2", "Variant$macrocall$1$ebnf$3", "Variant$macrocall$2"],
			postprocess: P.many,
		},
		{ name: "Variant", symbols: [lexer.has("bar") ? { type: "bar" } : bar, "Variant$macrocall$1"], postprocess: P.variant },
		{ name: "KeyVal$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "KeyVal$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "KeyVal$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "KeyVal$ebnf$2", symbols: [], postprocess: () => null },
		{
			name: "KeyVal",
			symbols: ["Identifier", "KeyVal$ebnf$1", lexer.has("colon") ? { type: "colon" } : colon, "KeyVal$ebnf$2", "TypeExpr"],
			postprocess: P.keyval,
		},
		{ name: "SchemaPair$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "SchemaPair$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "SchemaPair$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "SchemaPair$ebnf$2", symbols: [], postprocess: () => null },
		{
			name: "SchemaPair",
			symbols: [
				"Identifier",
				"SchemaPair$ebnf$1",
				lexer.has("colon") ? { type: "colon" } : colon,
				lexer.has("colon") ? { type: "colon" } : colon,
				"SchemaPair$ebnf$2",
				"TypeExpr",
			],
			postprocess: P.keyval,
		},
		{ name: "Assignment$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Assignment$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Assignment$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Assignment$ebnf$2", symbols: [], postprocess: () => null },
		{
			name: "Assignment",
			symbols: ["Identifier", "Assignment$ebnf$1", lexer.has("equals") ? { type: "equals" } : equals, "Assignment$ebnf$2", "TypeExpr"],
			postprocess: P.keyval,
		},
		{ name: "Projection", symbols: ["TypeExpr", lexer.has("dot") ? { type: "dot" } : dot, "Identifier"], postprocess: P.Projection },
		{ name: "Projection", symbols: [lexer.has("dot") ? { type: "dot" } : dot, "Identifier"], postprocess: P.Projection },
		{ name: "Injection$macrocall$2$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$2$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$2$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$2$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$2$macrocall$2", symbols: ["Assignment"] },
		{ name: "Injection$macrocall$2$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Injection$macrocall$2$macrocall$2",
				"Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Injection$macrocall$2$macrocall$3",
			],
		},
		{
			name: "Injection$macrocall$2$macrocall$1$ebnf$1",
			symbols: ["Injection$macrocall$2$macrocall$1$ebnf$1", "Injection$macrocall$2$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$2$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Injection$macrocall$2$macrocall$1",
			symbols: [
				"Injection$macrocall$2$macrocall$1$ebnf$1",
				"Injection$macrocall$2$macrocall$1$ebnf$2",
				"Injection$macrocall$2$macrocall$1$ebnf$3",
				"Injection$macrocall$2$macrocall$2",
			],
			postprocess: P.many,
		},
		{
			name: "Injection$macrocall$2",
			symbols: [
				"Injection$macrocall$2$ebnf$1",
				"TypeExpr",
				"Injection$macrocall$2$ebnf$2",
				lexer.has("bar") ? { type: "bar" } : bar,
				"Injection$macrocall$2$macrocall$1",
			],
		},
		{ name: "Injection$macrocall$1$macrocall$2", symbols: ["Injection$macrocall$2"] },
		{ name: "Injection$macrocall$1$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Injection$macrocall$1$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Injection$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Injection$macrocall$1$macrocall$1",
			symbols: [
				"Injection$macrocall$1$macrocall$3",
				"Injection$macrocall$1$macrocall$2",
				"Injection$macrocall$1$macrocall$1$ebnf$1",
				"Injection$macrocall$1$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "Injection$macrocall$1", symbols: ["Injection$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Injection", symbols: ["Injection$macrocall$1"], postprocess: P.Injection },
		{ name: "Injection$macrocall$4$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$4$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$4$macrocall$2", symbols: ["Assignment"] },
		{ name: "Injection$macrocall$4$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Injection$macrocall$4$macrocall$2",
				"Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Injection$macrocall$4$macrocall$3",
			],
		},
		{
			name: "Injection$macrocall$4$macrocall$1$ebnf$1",
			symbols: ["Injection$macrocall$4$macrocall$1$ebnf$1", "Injection$macrocall$4$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$4$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Injection$macrocall$4$macrocall$1",
			symbols: [
				"Injection$macrocall$4$macrocall$1$ebnf$1",
				"Injection$macrocall$4$macrocall$1$ebnf$2",
				"Injection$macrocall$4$macrocall$1$ebnf$3",
				"Injection$macrocall$4$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "Injection$macrocall$4", symbols: ["Injection$macrocall$4$ebnf$1", lexer.has("bar") ? { type: "bar" } : bar, "Injection$macrocall$4$macrocall$1"] },
		{ name: "Injection$macrocall$3$macrocall$2", symbols: ["Injection$macrocall$4"] },
		{ name: "Injection$macrocall$3$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Injection$macrocall$3$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Injection$macrocall$3$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Injection$macrocall$3$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Injection$macrocall$3$macrocall$1",
			symbols: [
				"Injection$macrocall$3$macrocall$3",
				"Injection$macrocall$3$macrocall$2",
				"Injection$macrocall$3$macrocall$1$ebnf$1",
				"Injection$macrocall$3$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "Injection$macrocall$3", symbols: ["Injection$macrocall$3$macrocall$1"], postprocess: P.enclosed },
		{ name: "Injection", symbols: ["Injection$macrocall$3"], postprocess: P.Injection },
		{ name: "Tagged$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Tagged$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Tagged", symbols: [lexer.has("colon") ? { type: "colon" } : colon, "Identifier", "Tagged$ebnf$1", "TypeExpr"], postprocess: P.tagged },
		{ name: "Block$macrocall$2$macrocall$2", symbols: ["Statement"] },
		{ name: "Block$macrocall$2$macrocall$3", symbols: [lexer.has("semicolon") ? { type: "semicolon" } : semicolon] },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1", symbols: [] },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"Block$macrocall$2$macrocall$2",
				"Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"Block$macrocall$2$macrocall$3",
			],
		},
		{
			name: "Block$macrocall$2$macrocall$1$ebnf$1",
			symbols: ["Block$macrocall$2$macrocall$1$ebnf$1", "Block$macrocall$2$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "Block$macrocall$2$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Block$macrocall$2$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "Block$macrocall$2$macrocall$1",
			symbols: [
				"Block$macrocall$2$macrocall$1$ebnf$1",
				"Block$macrocall$2$macrocall$1$ebnf$2",
				"Block$macrocall$2$macrocall$1$ebnf$3",
				"Block$macrocall$2$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "Block$macrocall$2$ebnf$1", symbols: ["Return"], postprocess: id },
		{ name: "Block$macrocall$2$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Block$macrocall$2",
			symbols: ["Block$macrocall$2$macrocall$1", lexer.has("semicolon") ? { type: "semicolon" } : semicolon, "Block$macrocall$2$ebnf$1"],
		},
		{ name: "Block$macrocall$1$macrocall$2", symbols: ["Block$macrocall$2"] },
		{ name: "Block$macrocall$1$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Block$macrocall$1$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Block$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Block$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Block$macrocall$1$macrocall$1",
			symbols: ["Block$macrocall$1$macrocall$3", "Block$macrocall$1$macrocall$2", "Block$macrocall$1$macrocall$1$ebnf$1", "Block$macrocall$1$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Block$macrocall$1", symbols: ["Block$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "Block", symbols: ["Block$macrocall$1"], postprocess: P.Block },
		{ name: "Block$macrocall$4", symbols: ["Return"] },
		{ name: "Block$macrocall$3$macrocall$2", symbols: ["Block$macrocall$4"] },
		{ name: "Block$macrocall$3$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "Block$macrocall$3$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "Block$macrocall$3$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Block$macrocall$3$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "Block$macrocall$3$macrocall$1",
			symbols: ["Block$macrocall$3$macrocall$3", "Block$macrocall$3$macrocall$2", "Block$macrocall$3$macrocall$1$ebnf$1", "Block$macrocall$3$macrocall$4"],
			postprocess: P.unwrap,
		},
		{ name: "Block$macrocall$3", symbols: ["Block$macrocall$3$macrocall$1"], postprocess: P.enclosed },
		{ name: "Block", symbols: ["Block$macrocall$3"], postprocess: P.Block },
		{ name: "Statement", symbols: ["Ann"], postprocess: P.Expr },
		{ name: "Statement", symbols: ["Letdec"], postprocess: id },
		{ name: "Return$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Return$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Return$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Return$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Return$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws] },
		{ name: "Return$ebnf$3", symbols: ["Return$ebnf$3", lexer.has("ws") ? { type: "ws" } : ws], postprocess: d => d[0].concat([d[1]]) },
		{
			name: "Return",
			symbols: ["Return$ebnf$1", "Return$ebnf$2", { literal: "return" }, "Return$ebnf$3", "Ann", lexer.has("semicolon") ? { type: "semicolon" } : semicolon],
			postprocess: P.Return,
		},
		{ name: "Letdec$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Letdec$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Letdec$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Letdec$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Letdec$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "Letdec",
			symbols: [
				{ literal: "let" },
				lexer.has("ws") ? { type: "ws" } : ws,
				"Identifier",
				"Letdec$ebnf$1",
				"Letdec$ebnf$2",
				lexer.has("equals") ? { type: "equals" } : equals,
				"Letdec$ebnf$3",
				"Letdec$ebnf$4",
				"Ann",
			],
			postprocess: P.LetDec,
		},
		{ name: "Letdec$ebnf$5", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Letdec$ebnf$5", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$6", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Letdec$ebnf$6", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$7", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Letdec$ebnf$7", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$8", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Letdec$ebnf$8", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$9", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Letdec$ebnf$9", symbols: [], postprocess: () => null },
		{ name: "Letdec$ebnf$10", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Letdec$ebnf$10", symbols: [], postprocess: () => null },
		{
			name: "Letdec",
			symbols: [
				{ literal: "let" },
				lexer.has("ws") ? { type: "ws" } : ws,
				"Identifier",
				"Letdec$ebnf$5",
				"Letdec$ebnf$6",
				lexer.has("colon") ? { type: "colon" } : colon,
				"Letdec$ebnf$7",
				"TypeExpr",
				"Letdec$ebnf$8",
				"Letdec$ebnf$9",
				lexer.has("equals") ? { type: "equals" } : equals,
				"Letdec$ebnf$10",
				"TypeExpr",
			],
			postprocess: P.LetDec,
		},
		{ name: "Identifier", symbols: [lexer.has("variable") ? { type: "variable" } : variable], postprocess: P.Name },
		{ name: "Quantity", symbols: [{ literal: "1" }], postprocess: () => Q.One },
		{ name: "Quantity", symbols: [{ literal: "0" }], postprocess: () => Q.Zero },
		{ name: "Quantity", symbols: [{ literal: "*" }], postprocess: () => Q.Many },
		{ name: "Match$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws] },
		{ name: "Match$ebnf$1", symbols: ["Match$ebnf$1", lexer.has("ws") ? { type: "ws" } : ws], postprocess: d => d[0].concat([d[1]]) },
		{ name: "Match$ebnf$2", symbols: ["Alt"] },
		{ name: "Match$ebnf$2", symbols: ["Match$ebnf$2", "Alt"], postprocess: d => d[0].concat([d[1]]) },
		{ name: "Match", symbols: [{ literal: "match" }, "Match$ebnf$1", "TypeExpr", "Match$ebnf$2"], postprocess: P.Match },
		{ name: "Alt$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "Alt$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Alt$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Alt$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "Alt$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Alt$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "Alt$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Alt$ebnf$4", symbols: [], postprocess: () => null },
		{ name: "Alt$ebnf$5", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "Alt$ebnf$5", symbols: [], postprocess: () => null },
		{
			name: "Alt",
			symbols: [
				"Alt$ebnf$1",
				"Alt$ebnf$2",
				lexer.has("bar") ? { type: "bar" } : bar,
				"Alt$ebnf$3",
				"Pattern",
				"Alt$ebnf$4",
				lexer.has("arrow") ? { type: "arrow" } : arrow,
				"Alt$ebnf$5",
				"TypeExpr",
			],
			postprocess: P.Alternative,
		},
		{ name: "Pattern$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "Pattern$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "Pattern", symbols: ["PatKeyVal", "Pattern$ebnf$1"], postprocess: P.Pattern.Variant },
		{ name: "Pattern", symbols: ["PatAtom"], postprocess: id },
		{ name: "PatAtom", symbols: ["Identifier"], postprocess: P.Pattern.Var },
		{ name: "PatAtom", symbols: ["Literal"], postprocess: P.Pattern.Lit },
		{ name: "PatAtom$macrocall$2$macrocall$2", symbols: ["PatAtom"] },
		{ name: "PatAtom$macrocall$2$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1", symbols: [] },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"PatAtom$macrocall$2$macrocall$2",
				"PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"PatAtom$macrocall$2$macrocall$3",
			],
		},
		{
			name: "PatAtom$macrocall$2$macrocall$1$ebnf$1",
			symbols: ["PatAtom$macrocall$2$macrocall$1$ebnf$1", "PatAtom$macrocall$2$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$2$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$2$macrocall$1",
			symbols: [
				"PatAtom$macrocall$2$macrocall$1$ebnf$1",
				"PatAtom$macrocall$2$macrocall$1$ebnf$2",
				"PatAtom$macrocall$2$macrocall$1$ebnf$3",
				"PatAtom$macrocall$2$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "PatAtom$macrocall$2$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "PatAtom$macrocall$2$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$2", symbols: ["PatAtom$macrocall$2$macrocall$1", "PatAtom$macrocall$2$ebnf$1"] },
		{ name: "PatAtom$macrocall$1$macrocall$2", symbols: ["PatAtom$macrocall$2"] },
		{ name: "PatAtom$macrocall$1$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "PatAtom$macrocall$1$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "PatAtom$macrocall$1$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$1$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$1$macrocall$1",
			symbols: [
				"PatAtom$macrocall$1$macrocall$3",
				"PatAtom$macrocall$1$macrocall$2",
				"PatAtom$macrocall$1$macrocall$1$ebnf$1",
				"PatAtom$macrocall$1$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "PatAtom$macrocall$1", symbols: ["PatAtom$macrocall$1$macrocall$1"], postprocess: P.enclosed },
		{ name: "PatAtom", symbols: ["PatAtom$macrocall$1"], postprocess: P.Pattern.Tuple },
		{ name: "PatAtom$macrocall$4$macrocall$2", symbols: ["PatKeyVal"] },
		{ name: "PatAtom$macrocall$4$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1", symbols: [] },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"PatAtom$macrocall$4$macrocall$2",
				"PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"PatAtom$macrocall$4$macrocall$3",
			],
		},
		{
			name: "PatAtom$macrocall$4$macrocall$1$ebnf$1",
			symbols: ["PatAtom$macrocall$4$macrocall$1$ebnf$1", "PatAtom$macrocall$4$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$4$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$4$macrocall$1",
			symbols: [
				"PatAtom$macrocall$4$macrocall$1$ebnf$1",
				"PatAtom$macrocall$4$macrocall$1$ebnf$2",
				"PatAtom$macrocall$4$macrocall$1$ebnf$3",
				"PatAtom$macrocall$4$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "PatAtom$macrocall$4$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "PatAtom$macrocall$4$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$4", symbols: ["PatAtom$macrocall$4$macrocall$1", "PatAtom$macrocall$4$ebnf$1"] },
		{ name: "PatAtom$macrocall$3$macrocall$2", symbols: ["PatAtom$macrocall$4"] },
		{ name: "PatAtom$macrocall$3$macrocall$3", symbols: [lexer.has("lbrace") ? { type: "lbrace" } : lbrace] },
		{ name: "PatAtom$macrocall$3$macrocall$4", symbols: [lexer.has("rbrace") ? { type: "rbrace" } : rbrace] },
		{ name: "PatAtom$macrocall$3$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$3$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$3$macrocall$1",
			symbols: [
				"PatAtom$macrocall$3$macrocall$3",
				"PatAtom$macrocall$3$macrocall$2",
				"PatAtom$macrocall$3$macrocall$1$ebnf$1",
				"PatAtom$macrocall$3$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "PatAtom$macrocall$3", symbols: ["PatAtom$macrocall$3$macrocall$1"], postprocess: P.enclosed },
		{ name: "PatAtom", symbols: ["PatAtom$macrocall$3"], postprocess: P.Pattern.Struct },
		{ name: "PatAtom$macrocall$6$macrocall$2", symbols: ["PatAtom"] },
		{ name: "PatAtom$macrocall$6$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1", symbols: [] },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"PatAtom$macrocall$6$macrocall$2",
				"PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"PatAtom$macrocall$6$macrocall$3",
			],
		},
		{
			name: "PatAtom$macrocall$6$macrocall$1$ebnf$1",
			symbols: ["PatAtom$macrocall$6$macrocall$1$ebnf$1", "PatAtom$macrocall$6$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$6$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$6$macrocall$1",
			symbols: [
				"PatAtom$macrocall$6$macrocall$1$ebnf$1",
				"PatAtom$macrocall$6$macrocall$1$ebnf$2",
				"PatAtom$macrocall$6$macrocall$1$ebnf$3",
				"PatAtom$macrocall$6$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "PatAtom$macrocall$6", symbols: ["PatAtom$macrocall$6$macrocall$1"] },
		{ name: "PatAtom$macrocall$5$macrocall$2", symbols: ["PatAtom$macrocall$6"] },
		{ name: "PatAtom$macrocall$5$macrocall$3", symbols: [lexer.has("lbracket") ? { type: "lbracket" } : lbracket] },
		{ name: "PatAtom$macrocall$5$macrocall$4", symbols: [lexer.has("rbracket") ? { type: "rbracket" } : rbracket] },
		{ name: "PatAtom$macrocall$5$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$5$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$5$macrocall$1",
			symbols: [
				"PatAtom$macrocall$5$macrocall$3",
				"PatAtom$macrocall$5$macrocall$2",
				"PatAtom$macrocall$5$macrocall$1$ebnf$1",
				"PatAtom$macrocall$5$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "PatAtom$macrocall$5", symbols: ["PatAtom$macrocall$5$macrocall$1"], postprocess: P.enclosed },
		{ name: "PatAtom$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "PatAtom$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom", symbols: ["PatAtom$macrocall$5", "PatAtom$ebnf$1"], postprocess: P.Pattern.List },
		{ name: "PatAtom$macrocall$8$macrocall$2", symbols: ["PatKeyVal"] },
		{ name: "PatAtom$macrocall$8$macrocall$3", symbols: [lexer.has("comma") ? { type: "comma" } : comma] },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1", symbols: [] },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$3", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$4", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1",
			symbols: [
				"PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$1",
				"PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$2",
				"PatAtom$macrocall$8$macrocall$2",
				"PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$3",
				"PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1$ebnf$4",
				"PatAtom$macrocall$8$macrocall$3",
			],
		},
		{
			name: "PatAtom$macrocall$8$macrocall$1$ebnf$1",
			symbols: ["PatAtom$macrocall$8$macrocall$1$ebnf$1", "PatAtom$macrocall$8$macrocall$1$ebnf$1$subexpression$1"],
			postprocess: d => d[0].concat([d[1]]),
		},
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$2", symbols: [lexer.has("NL") ? { type: "NL" } : NL], postprocess: id },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$2", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$3", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$8$macrocall$1$ebnf$3", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$8$macrocall$1",
			symbols: [
				"PatAtom$macrocall$8$macrocall$1$ebnf$1",
				"PatAtom$macrocall$8$macrocall$1$ebnf$2",
				"PatAtom$macrocall$8$macrocall$1$ebnf$3",
				"PatAtom$macrocall$8$macrocall$2",
			],
			postprocess: P.many,
		},
		{ name: "PatAtom$macrocall$8$ebnf$1", symbols: ["RowTail"], postprocess: id },
		{ name: "PatAtom$macrocall$8$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatAtom$macrocall$8", symbols: ["PatAtom$macrocall$8$macrocall$1", "PatAtom$macrocall$8$ebnf$1"] },
		{ name: "PatAtom$macrocall$7$macrocall$2", symbols: ["PatAtom$macrocall$8"] },
		{ name: "PatAtom$macrocall$7$macrocall$3", symbols: [lexer.has("lbracket") ? { type: "lbracket" } : lbracket] },
		{ name: "PatAtom$macrocall$7$macrocall$4", symbols: [lexer.has("rbracket") ? { type: "rbracket" } : rbracket] },
		{ name: "PatAtom$macrocall$7$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$7$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$7$macrocall$1",
			symbols: [
				"PatAtom$macrocall$7$macrocall$3",
				"PatAtom$macrocall$7$macrocall$2",
				"PatAtom$macrocall$7$macrocall$1$ebnf$1",
				"PatAtom$macrocall$7$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "PatAtom$macrocall$7", symbols: ["PatAtom$macrocall$7$macrocall$1"], postprocess: P.enclosed },
		{ name: "PatAtom", symbols: ["PatAtom$macrocall$7"], postprocess: P.Pattern.Row },
		{ name: "PatAtom", symbols: ["Wildcard"], postprocess: P.Pattern.Wildcard },
		{ name: "PatAtom$macrocall$10", symbols: ["Pattern"] },
		{ name: "PatAtom$macrocall$9$macrocall$2", symbols: ["PatAtom$macrocall$10"] },
		{ name: "PatAtom$macrocall$9$macrocall$3", symbols: [lexer.has("lparens") ? { type: "lparens" } : lparens] },
		{ name: "PatAtom$macrocall$9$macrocall$4", symbols: [lexer.has("rparens") ? { type: "rparens" } : rparens] },
		{ name: "PatAtom$macrocall$9$macrocall$1$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatAtom$macrocall$9$macrocall$1$ebnf$1", symbols: [], postprocess: () => null },
		{
			name: "PatAtom$macrocall$9$macrocall$1",
			symbols: [
				"PatAtom$macrocall$9$macrocall$3",
				"PatAtom$macrocall$9$macrocall$2",
				"PatAtom$macrocall$9$macrocall$1$ebnf$1",
				"PatAtom$macrocall$9$macrocall$4",
			],
			postprocess: P.unwrap,
		},
		{ name: "PatAtom$macrocall$9", symbols: ["PatAtom$macrocall$9$macrocall$1"], postprocess: P.enclosed },
		{ name: "PatAtom", symbols: ["PatAtom$macrocall$9"], postprocess: P.extract },
		{ name: "PatKeyVal$ebnf$1", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatKeyVal$ebnf$1", symbols: [], postprocess: () => null },
		{ name: "PatKeyVal$ebnf$2", symbols: [lexer.has("ws") ? { type: "ws" } : ws], postprocess: id },
		{ name: "PatKeyVal$ebnf$2", symbols: [], postprocess: () => null },
		{
			name: "PatKeyVal",
			symbols: ["Identifier", "PatKeyVal$ebnf$1", lexer.has("colon") ? { type: "colon" } : colon, "PatKeyVal$ebnf$2", "Pattern"],
			postprocess: P.keyvalPat,
		},
		{ name: "Wildcard", symbols: [lexer.has("hole") ? { type: "hole" } : hole], postprocess: P.Wildcard },
		{ name: "Literal", symbols: ["String"], postprocess: P.Str },
		{ name: "Literal", symbols: ["Number"], postprocess: P.Num },
		{ name: "Literal", symbols: [{ literal: "Type" }], postprocess: P.Type },
		{ name: "Literal", symbols: [{ literal: "Unit" }], postprocess: P.Unit("type") },
		{ name: "Literal", symbols: [{ literal: "*" }], postprocess: P.Unit("value") },
		{ name: "Literal", symbols: [{ literal: "Row" }], postprocess: P.LitRow },
		{ name: "Number", symbols: ["Int", lexer.has("dot") ? { type: "dot" } : dot, "Int"], postprocess: id },
		{ name: "Number", symbols: ["Int"], postprocess: id },
		{ name: "Int", symbols: [lexer.has("digit") ? { type: "digit" } : digit], postprocess: P.sourceLoc },
		{ name: "String", symbols: [lexer.has("string") ? { type: "string" } : string], postprocess: P.sourceLoc },
	],
	ParserStart: "Script",
};

export default grammar;
